version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres-mind
    restart: always
    networks:
      - postgres-network
    ports:
      - 5432:5432
    volumes:
      - postgres-mind:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass123

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin-mind
    networks:
        - postgres-network
    ports:
        - 15432:80
    environment:
        - PGADMIN_DEFAULT_EMAIL=nimoura1@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=pg123!

networks:
  postgres-network:
    driver: bridge
    name: postgres-network

volumes:
  postgres-mind:
    external: false
    name: postgres-mind